### PR TITLE
Add support for Offline mode with NekR/offline-plugin

### PR DESCRIPTION
**Pull request by Luchillo**
This PR will add support for offline mode with this plugin: [NekR/offline-plugin](https://github.com/NekR/offline-plugin).

Relate to https://github.com/AngularClass/angular2-webpack-starter/issues/728 for the discussion about which plugin to choose as well as other very desirable features.

### CODE REVIEW

**Comment by katallaxie** [comment]
Good work. I would be great to have this as patch to the start. So in case one would want to have this feature, without making it the standard.

**Comment by Luchillo** [comment]
2 questions, i do think this is a nice default, but as you say it isn't for everyone, so how do we make it a patch?

What's that about checks? is that the testing of this repo with travis? if so i think it was already broken before i started to edit this feature.

**Comment by NekR** [comment]
You probably don't need `offline-plugin` in dev-mode, only in production. It's especially useless with `wepback-dev-server`. Production build anyway must be tested locally too, so SW/AppCache could be tested at that moment.

**Comment by Luchillo** [comment]
Sooo, using the plugin runtime only in prod mode, and adding tests? to tell you the truth i haven't mess around a lot with testing in JS, i have done it in Ruby and Rails but not in JS, so i don't feel like making tests for that, i'll probably make very bad tests and you guys will end up rewriting them.

**Comment by NekR** [comment]
What's happening with this issue anyway?

**Comment by Luchillo** [comment]
Oh i'm sorry about that story feed up there, i'm just trying to update to V6 branch with the Offline plugin working, however i'm having issues with the DLL's to be included in the browser cache.

**Comment by katallaxie** [comment]
@Luchillo I close the PR, because `v6` is not yet destined to move to `master`. You should push to my `v6` if it works.

**Comment by Luchillo** [comment]
Actually i didn't want to push all that, i tough the only thing that get's in the PR is when i make the PR, not later commits, so all along it was commits not intended for this PR.

**Comment by katallaxie** [comment]
Everything that is in the branch is this branch and not in the master is merged.

**Pull request closed without merging**
