### PR TITLE
Make Webpack Upgradable and DRY

### PR DESCRIPTION
**Pull request by Spittal**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
The webpack configuration has been changed so that components of the configuration that is shared between production and development are now in one file. It makes the files more cohesive and easier to update. 

I've tried introducing this before, but was rejected on grounds of complexity. I would like to argue that this configuration is yes slightly more complex (not anymore complex than other parts of this starter pack) but makes it much easier to to merge in changes from this repo into existing projects. Not only does it allow you put your custom loaders in a single file, but also the "config" object having the ability to be passed around means that you can merge changes from this repo much easier without breaking some "application specific" changes.

* **What is the current behavior?** (You can also link to an open issue here)
There is a lots of duplicate code in the webpack configurations.

* **What is the new behavior (if this is a feature change)?**
Made the webpack conmfiguration more dry, and more scalable.

* **Other information**:
I've been trying to stay up to date with the latest polyfills, and beta versions of Angular while developing an application, It's important to me that I am able to quickly apply changes made in this repo to my own applications. This PR would make that process much faster for me.

### CODE REVIEW

**Comment by gdi2290** [comment]
this is fine having a common/base/default config but only if we create a new copy
```es6
var defaultConfig = require('webpack.defaults.js');

module.exports = webpackMerge(defaultConfig, {
  devtool: 'eval'
});
```
that's more familiar to new webpack devs

**Comment by mbcooper** [comment]
+1

**Comment by Spittal** [comment]
Hey @gdi2290 I was able to refactor using webpack merge. Tested with `npm run server` `npm run build:prod` and `npm run build:dev`. Seems to be working great.

**Comment by fishfillet** [comment]
+1

**Comment by tsm91** [comment]
@Spittal @gdi2290 why not `Object.assign`? im not a webpack expert, but the config is just an object

`Object.assign({}, obj1, obj2)` will create a new object

**Comment by gdi2290** [comment]
thanks!

**Pull request merged**
