### PR TITLE
Webpack css chunks integration for production builds

### PR DESCRIPTION
**Pull request by yannvr**
Add CSS support for production builds according to the webpack doc: https://webpack.github.io/docs/stylesheets.html

### CODE REVIEW

**Comment by gdi2290** [comment]
@yannvr can you add this to the wiki with a link to this PR
https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-css-chunks-integration

**Comment by yannvr** [comment]
WIKI section filled.
Cheers

**Comment by gdi2290** [comment]
thanks! I won't be able to merge this because the developer will be missing out on the features provided by Angular 2 with style encapsulation

**Comment by yannvr** [comment]
Have you tried it? Encapsulation works perfectly fine with CSS production
build. I was merely mentioning a special case in the wiki.


Yann

**Pull request closed without merging**
