### PR TITLE
chore(yarn): add yarn files to gitignore

### PR DESCRIPTION
**Pull request by d3viant0ne**
* **What is the new behavior (if this is a feature change)?**
Ignores yarn output 

* **Other information**:

Per https://github.com/AngularClass/angular2-webpack-starter/commit/5db20a697bee643758ce597c8b9f7059f398e462#commitcomment-20016692

### CODE REVIEW

**Comment by katallaxie** [comment]
See https://github.com/yarnpkg/yarn/issues/1583 that is a bad idea, when it comes to really use `yarn`.

**Comment by d3viant0ne** [comment]
@katallaxie - The yarn.lock was removed by @gdi2290. The ignore for yarn is also at his request.

**Comment by karolmie1** [comment]
@d3viant0ne Yeah It is really bad idea. yarn.lock is like one of the most important reasons to use yarn. 
I very often had this problem - I've downloaded old repo from github and I started to fire it up, but I couldn't manage to get it working, because author used older version of npm packages and the project won't compile anymore. (this also happend to me on material2 branch here if I remember correctly)

yarn.lock is very important and essential.

It may make pull requests and diffs ugly though.
Worry not, there is better solution than to remove it altogeter!

.gitattributes:
yarn.lock -diff

yarn.lock will be treated as binary from now on, won't be shown in difs and counted in lines changed if you care about such statistics.

**Comment by katallaxie** [comment]
@d3viant0ne yep! you can remove it, but you should not `.gitignore` it, as people really use it in their projects.

**Comment by karolmie1** [comment]
@katallaxie I will create a pull request with .gitattributes solution in a moment, you can check if you like it.

**Comment by gdi2290** [comment]
yeah I didn't see that with yarn. let's just keep it out of the initial repo

**Comment by irfannnn1** [comment]
,m

**Pull request closed without merging**
