### PR TITLE
fix: Rename export for detail module

### PR DESCRIPTION
**Pull request by stevenjob**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Just a rename

### CODE REVIEW

**Comment by colinskow** [comment]
Also default needs to be removed because it is incompatible with the AoT compiler.
https://github.com/AngularClass/angular2-webpack-starter/pull/1298/files#diff-15e96909d26305ab86756a9d68100c27L25

I agree that `DetailModule` is a better name. If the maintainers agree I can add a commit to my PR. The link to the module in `app.routes.ts` also needs to be updated.

**Comment by d3viant0ne** [comment]
@stevenjob / @colinskow - I'll merge yours as it is, then Steven can rebase & rename the component as discussed above.

**Comment by katallaxie** [comment]
👍

**Comment by stevenjob** [comment]
Done 👍

**Pull request merged**
