### PR TITLE
Feature/happy lint

### PR DESCRIPTION
**Pull request by michaeljota**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

tslint update
- **What is the current behavior?** (You can also link to an open issue here)
  - Tslint 3.9.x have a bug while dealing with wilcards
  - Codelyzer rules have not been used
  - Recommended rules hard coded.
- **What is the new behavior (if this is a feature change)?**
  - TSlint update to `@next`
  - Recommended Codelyzer rules being used in a separate file.
  - Extend recommended rules.
  - Update all code to follow new rules
- **Other information**:

This somehow is related to #1091 and #1084. But instead of **just follow the style guide** I updated the TSLint to linter the style guide with `codelyzer`.

### CODE REVIEW

**Comment by michaeljota** [comment]
Ok. I did not see #185 before this. BUT, there is now an official [Angular 2 Style Guide](https://angular.io/docs/ts/latest/guide/style-guide.html) there is even a TSLint plugin to use them, that by the way this seed "use", named [codelyzer](https://github.com/mgechev/codelyzer), with the apropiated rules, everything should be fine. 

I just wanted to help.

**Comment by katallaxie** [comment]
I did merged #185 and we have to adjust some things.

**Comment by michaeljota** [comment]
I saw it. But as I say, this is not just "styling" the seed to Angular2 style guide, but instead, linting it, and fix the files to the linting, to Codelyzer, that happens to be the plugin to follow Angular2 style guide.

**Comment by michaeljota** [comment]
Now that you merge #1091 I guess this have better chances, since now it only config the linter to use recommended rules, from TSLint and Codelyzer.

**Comment by michaeljota** [comment]
I could do that. I guess that it's better if it's clear where the rules come from, if there are coming from external plugin.

**Comment by katallaxie** [comment]
@michaeljota I just thought the same, yet coming from a different angle. I was think that in this starter, a single point for the rules is the way to go. So, I would just keeping everything in `tslint.json`.

**Comment by michaeljota** [comment]
I see your point. I have a question then, should the recommended rules still explicitly be available or should they be extended?

**Comment by d3viant0ne** [comment]
Other dependencies do not support tslint 4.x, resubmit a PR when both Codelyzer & tslint-loader all support the newer version of tslint. Merging something for 4.x / @next will fail peerDeps breaking nodejs 4.x builds.

**Pull request closed without merging**
