### PR TITLE
(feat) - WIP - experimental DDL Support

### PR DESCRIPTION
**Pull request by abhishekisnot**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
As described in #1330 

* **What is the new behavior (if this is a feature change)?**
Introduce Webpack DLL feature to speed up build times during DEV builds only.

* **Other information**:
As mentioned in the issue comments, this feature is worth having for large projects. This PR is an attempt to do this with minimal changes to common webpack config thereby trying to strike balance between huge config blocks and having to rewrite all of webpack common config.
This PR however does not address webpack blocks or ability to opt in/out.

**This PR is still WIP, please do not merge unless WIP label is removed from PR title**

**Note:** The DLLs currently do not work and needs more work. This PR is raised in an attempt to get feedback per the issues comments on #1330. Currently I see below errors on console:
screen shot 2017-01-04 at 12 18 43 am

cc: @colinskow, @shlomiassaf, @d3viant0ne

### CODE REVIEW

**Comment by katallaxie** [comment]
Perhaps this project of mine would help [angular2-preboot](https://github.com/katallaxie/angular2-preboot). It has `dll` support and is fully Typescript.

**Comment by colinskow** [comment]
We will need to add the DLL build to our test suite before this is merged to prevent DLL from breaking accidentally in the future.

**Comment by colinskow** [comment]
@abhishekisnot I believe you have to copy the dll files into the `dist` directory at the beginning of the build before you can reference them.

**Comment by abhishekisnot** [comment]
Awesome. Thank you @colinskow. I'm closing this PR in favor of #1341. Do we have numbers on savings in dev build time? I mean build times before and after introducing DLL plugins?

**Pull request closed without merging**
