### PR TITLE
update material to alpha.9

### PR DESCRIPTION
**Pull request by dweitz43**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature branch update

* **What is the current behavior?** (You can also link to an open issue here)
material branch has fallen behind master and is out of date with current material alpha version

* **What is the new behavior (if this is a feature change)?**
update material branch to include latest changes to master and to material alpha.9

* **Other information**:

### CODE REVIEW

**Comment by kodeine** [comment]
please merge this :)

**Comment by michaeljota** [comment]
I don't think this should be merge. There is some much files that changes outside of the described scope. The update needs to be done, but I guess that this need only the really necessary files to be updated.

**Comment by dweitz43** [comment]
@michaeljota the changes not related to material are to bring the branch up to date with the master branch. with that said, this pr is probably out of date by now as there have been more changes made to the master branch

**Comment by michaeljota** [comment]
That's what I mean. You probably should fork, and create a branch, make changes in that branch, and push the changes. If you want to pull changes from here, you should `upstream` it. However, you should always rebase your code on top of the `pull`s you have to make.

**Pull request closed without merging**
