### PR TITLE
use tslint-loader on save

### PR DESCRIPTION
**Pull request by seiyria**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
TSLint will now run on file save (most things will show up as warnings in the terminal).

* **What is the current behavior?** (You can also link to an open issue here)
You have to run TSLint manually.

* **What is the new behavior (if this is a feature change)?**
TSLint runs automatically on file save.

* **Other information**:
I found this particularly helpful because otherwise linting only happens on a CI server (since it wouldn't be enforced pre-push or pre-commit). This makes it easier to see what's going on. Coupled with an editor tslint plugin, this should be 💯/💯.

### CODE REVIEW

**Comment by seiyria** [comment]
Why only dev? This is useful on prod builds too.

**Comment by katallaxie** [comment]
@seiyria We do linting in the CI before moving to production. Or, in any case, before you go in production, you should have the CI tasks running. Thus, I see it as only helpful to have it running in dev, when debugging in the browser or console.

**Comment by seiyria** [comment]
pushed a change to move it to dev

**Comment by h3nnry** [comment]
Sorry for offtop, can any one help me pls and tell me how to use Bootstrap 4 and Sass with angular2-webpack-starter

**Comment by h3nnry** [comment]
also for the last commit on mac get the error:
angular2-webpack-starter/config/webpack.dev.js:105
         exclude: [/\.(spec|e2e)\.ts$/]
         ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at requireConfig (/web/yyy/angular2-webpack-starter/node_modules/webpack/bin/convert-argv.js:96:18)
    at /web/yyy/angular2-webpack-starter/node_modules/webpack/bin/convert-argv.js:109:17

**Comment by seiyria** [comment]
@h3nnry you'd have much better luck opening or searching through the issues than commenting on a merged PR.

**Pull request merged**
