### PR TITLE
misc: upgrade to ngc-webpack 1.1.0

### PR DESCRIPTION
**Pull request by shlomiassaf**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Upgrade to `ngc-webpack@1.1.0`

* **Other information**:
`ngc-webpack@1.1.0` comes with 2 major improvements:

  - Run the angular complier from the `NgcWebpackPlugin`  
this makes configuration easier, removes cli steps and provides more control over the compilation

  - Remove `@Component` resources (template/styles) from the bundle.  
This is actually a great improvement to bundle size...
For each `@Component` the AOT compiler compiles it creates new representation for the templates (html, styles) of that `@Components`. It means that there is no need for the source templates, they take a lot of space... **Webpack** bundles out source files and the compiler files (`ngfactory`) so we get 2 versions of the same template/style in our bundle.  
This feature is `NormalModuleReplacementPlugin` for identified resources... the templates are replaced with empty files.

@gdi2290 @d3viant0ne please review...

Although I did full tests and double checks I suggest we wait several days for people to test this before merging.

Thanks.

### CODE REVIEW

**Comment by JonnyBGod** [comment]
@gdi2290 Can you confirm if assets are being copied to dist?

**Comment by shlomiassaf** [comment]
@JonnyBGod are you asking regarding this pr?

What's not copied, that's very strange since the compiler has no business with the assets (:

**Comment by JonnyBGod** [comment]
Sorry not related assets problem is related to webpack-merge update will check that tomorrow.

But I am getting a different error actually related to this PR, compilation goes all well, but in browser:

```
Config env: production
vendor.2ef8b2e….bundle.js:9 EXCEPTION: Uncaught (in promise): Error: Cannot find module './about/about.module.ngfactory'.
Error: Cannot find module './about/about.module.ngfactory'.
    at p (http://localhost:8080/polyfills.909d6bf21031f1436c3f.bundle.js:2:24176)
    at n (http://localhost:8080/main.8efcced115f3d87397d5.bundle.js:3:503)
    at t.loadFactory (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:13:2819)
    at t.load (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:13:2418)
    at t.loadModuleFactory (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:3:29871)
    at t.load (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:3:29579)
    at http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9750
    at t.preload (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:8625)
    at t.preloadConfig (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9714)
    at t.processRoutes (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9519)
    at t.processRoutes (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9563)
    at t.processRoutes (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9439)
    at t.preload (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9152)
    at e.project (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9071)
    at e._tryNext (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:3:11304)
t.handleError @ vendor.2ef8b2e….bundle.js:9
next @ vendor.2ef8b2e….bundle.js:6
e.object.o @ vendor.2ef8b2e….bundle.js:2
e.__tryOrUnsub @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e._next @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e.emit @ vendor.2ef8b2e….bundle.js:2
t.triggerError @ vendor.2ef8b2e….bundle.js:5
onHandleError @ vendor.2ef8b2e….bundle.js:5
e.handleError @ polyfills.909d6bf….bundle.js:2
t.runGuarded @ polyfills.909d6bf….bundle.js:2
n @ polyfills.909d6bf….bundle.js:2
i @ polyfills.909d6bf….bundle.js:2
vendor.2ef8b2e….bundle.js:9 ORIGINAL STACKTRACE:
t.handleError @ vendor.2ef8b2e….bundle.js:9
next @ vendor.2ef8b2e….bundle.js:6
e.object.o @ vendor.2ef8b2e….bundle.js:2
e.__tryOrUnsub @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e._next @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e.emit @ vendor.2ef8b2e….bundle.js:2
t.triggerError @ vendor.2ef8b2e….bundle.js:5
onHandleError @ vendor.2ef8b2e….bundle.js:5
e.handleError @ polyfills.909d6bf….bundle.js:2
t.runGuarded @ polyfills.909d6bf….bundle.js:2
n @ polyfills.909d6bf….bundle.js:2
i @ polyfills.909d6bf….bundle.js:2
vendor.2ef8b2e….bundle.js:9 Error: Uncaught (in promise): Error: Cannot find module './about/about.module.ngfactory'.
Error: Cannot find module './about/about.module.ngfactory'.
    at p (polyfills.909d6bf….bundle.js:2)
    at n (main.8efcced….bundle.js:3)
    at t.loadFactory (vendor.2ef8b2e….bundle.js:13)
    at t.load (vendor.2ef8b2e….bundle.js:13)
    at t.loadModuleFactory (vendor.2ef8b2e….bundle.js:3)
    at t.load (vendor.2ef8b2e….bundle.js:3)
    at vendor.2ef8b2e….bundle.js:10
    at t.preload (vendor.2ef8b2e….bundle.js:10)
    at t.preloadConfig (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.preload (vendor.2ef8b2e….bundle.js:10)
    at e.project (vendor.2ef8b2e….bundle.js:10)
    at e._tryNext (vendor.2ef8b2e….bundle.js:3)
    at p (polyfills.909d6bf….bundle.js:2)
    at s (polyfills.909d6bf….bundle.js:2)
    at polyfills.909d6bf….bundle.js:2
    at e.invokeTask (polyfills.909d6bf….bundle.js:2)
    at Object.onInvokeTask (vendor.2ef8b2e….bundle.js:5)
    at e.invokeTask (polyfills.909d6bf….bundle.js:2)
    at t.runTask (polyfills.909d6bf….bundle.js:2)
    at i (polyfills.909d6bf….bundle.js:2)
t.handleError @ vendor.2ef8b2e….bundle.js:9
next @ vendor.2ef8b2e….bundle.js:6
e.object.o @ vendor.2ef8b2e….bundle.js:2
e.__tryOrUnsub @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e._next @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e.next @ vendor.2ef8b2e….bundle.js:1
e.emit @ vendor.2ef8b2e….bundle.js:2
t.triggerError @ vendor.2ef8b2e….bundle.js:5
onHandleError @ vendor.2ef8b2e….bundle.js:5
e.handleError @ polyfills.909d6bf….bundle.js:2
t.runGuarded @ polyfills.909d6bf….bundle.js:2
n @ polyfills.909d6bf….bundle.js:2
i @ polyfills.909d6bf….bundle.js:2
polyfills.909d6bf….bundle.js:2 Unhandled Promise rejection: Cannot find module './about/about.module.ngfactory'. ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot find module './about/about.module.ngfactory'.
    at p (polyfills.909d6bf….bundle.js:2)
    at n (main.8efcced….bundle.js:3)
    at t.loadFactory (vendor.2ef8b2e….bundle.js:13)
    at t.load (vendor.2ef8b2e….bundle.js:13)
    at t.loadModuleFactory (vendor.2ef8b2e….bundle.js:3)
    at t.load (vendor.2ef8b2e….bundle.js:3)
    at vendor.2ef8b2e….bundle.js:10
    at t.preload (vendor.2ef8b2e….bundle.js:10)
    at t.preloadConfig (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.preload (vendor.2ef8b2e….bundle.js:10)
    at e.project (vendor.2ef8b2e….bundle.js:10)
    at e._tryNext (vendor.2ef8b2e….bundle.js:3) Error: Cannot find module './about/about.module.ngfactory'.
    at p (http://localhost:8080/polyfills.909d6bf21031f1436c3f.bundle.js:2:24176)
    at n (http://localhost:8080/main.8efcced115f3d87397d5.bundle.js:3:503)
    at t.loadFactory (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:13:2819)
    at t.load (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:13:2418)
    at t.loadModuleFactory (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:3:29871)
    at t.load (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:3:29579)
    at http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9750
    at t.preload (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:8625)
    at t.preloadConfig (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9714)
    at t.processRoutes (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9519)
    at t.processRoutes (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9563)
    at t.processRoutes (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9439)
    at t.preload (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9152)
    at e.project (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:10:9071)
    at e._tryNext (http://localhost:8080/vendor.2ef8b2e00da3711b968a.bundle.js:3:11304)
r @ polyfills.909d6bf….bundle.js:2
n @ polyfills.909d6bf….bundle.js:2
i @ polyfills.909d6bf….bundle.js:2
polyfills.909d6bf….bundle.js:2 Error: Uncaught (in promise): Error: Cannot find module './about/about.module.ngfactory'.
Error: Cannot find module './about/about.module.ngfactory'.
    at p (polyfills.909d6bf….bundle.js:2)
    at n (main.8efcced….bundle.js:3)
    at t.loadFactory (vendor.2ef8b2e….bundle.js:13)
    at t.load (vendor.2ef8b2e….bundle.js:13)
    at t.loadModuleFactory (vendor.2ef8b2e….bundle.js:3)
    at t.load (vendor.2ef8b2e….bundle.js:3)
    at vendor.2ef8b2e….bundle.js:10
    at t.preload (vendor.2ef8b2e….bundle.js:10)
    at t.preloadConfig (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.preload (vendor.2ef8b2e….bundle.js:10)
    at e.project (vendor.2ef8b2e….bundle.js:10)
    at e._tryNext (vendor.2ef8b2e….bundle.js:3)
    at p (polyfills.909d6bf….bundle.js:2)
    at n (main.8efcced….bundle.js:3)
    at t.loadFactory (vendor.2ef8b2e….bundle.js:13)
    at t.load (vendor.2ef8b2e….bundle.js:13)
    at t.loadModuleFactory (vendor.2ef8b2e….bundle.js:3)
    at t.load (vendor.2ef8b2e….bundle.js:3)
    at vendor.2ef8b2e….bundle.js:10
    at t.preload (vendor.2ef8b2e….bundle.js:10)
    at t.preloadConfig (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.processRoutes (vendor.2ef8b2e….bundle.js:10)
    at t.preload (vendor.2ef8b2e….bundle.js:10)
    at e.project (vendor.2ef8b2e….bundle.js:10)
    at e._tryNext (vendor.2ef8b2e….bundle.js:3)
    at p (polyfills.909d6bf….bundle.js:2)
    at s (polyfills.909d6bf….bundle.js:2)
    at polyfills.909d6bf….bundle.js:2
    at e.invokeTask (polyfills.909d6bf….bundle.js:2)
    at Object.onInvokeTask (vendor.2ef8b2e….bundle.js:5)
    at e.invokeTask (polyfills.909d6bf….bundle.js:2)
    at t.runTask (polyfills.909d6bf….bundle.js:2)
    at i (polyfills.909d6bf….bundle.js:2)
r @ polyfills.909d6bf….bundle.js:2
n @ polyfills.909d6bf….bundle.js:2
i @ polyfills.909d6bf….bundle.js:2
```

Everything was ok with previous version.
It is too late now so I will investigate more after sleep.

**Comment by JonnyBGod** [comment]
Ok I figured out the problem and it is not really a problem with the PR.
It apparently just have more strict parsing or linting rules and was not accepting a malformed module.

Only problem is that it did not report any issues on compile. Apart from that it works fine.

**Comment by JonnyBGod** [comment]
Than again, no issues reported on dev or prod mode either...

**Pull request merged**
