### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by opporancisis**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Documentation fix

* **What is the current behavior?** (You can also link to an open issue here)
Incorect link to source file in the documentation - home.spec.ts

* **What is the new behavior (if this is a feature change)?**
Fixed link - home.component.spec.ts

* **Other information**:

home.spec.ts was renamed at some point, so it should be fixed in the documentation

### CODE REVIEW

**Comment by NatsuOnFire** [comment]
It is not only that to modify. All readme must be updated.
Here are some examples:

- Clone/Download the repo then edit app.ts inside /src/app/app.ts (404 app.ts doesn't exist)
- All file structure
- Dependencies (add node 6 and prevent from using node 7)
- Typescript 2

**Comment by gdi2290** [comment]
can one you @NatsuOnFire @opporancisis update the rest of the readme etc to reflect the changes?

**Comment by NatsuOnFire** [comment]
Sorry but I only know that this is no longer correct, I do not know how to modify it.

**Comment by opporancisis** [comment]
One more pull request created:
https://github.com/AngularClass/angular2-webpack-starter/pull/1325

**Pull request merged**
