### PR TITLE
update material2 branch

### PR DESCRIPTION
**Pull request by dweitz43**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
branch update

* **What is the current behavior?** (You can also link to an open issue here)
material2 branch has fallen behind master branch

* **What is the new behavior (if this is a feature change)?**
update material2 branch to latest master branch, including angular 2 final release

* **Other information**:

### CODE REVIEW

**Comment by louisscruz** [comment]
I just downloaded this and gave it a try. Seems to be working well (after fixing the webpack version fix specified here: https://github.com/AngularClass/angular2-webpack-starter/issues/1036)

**Comment by kodeine** [comment]
why its not merged yet?

**Comment by dweitz43** [comment]
@kodeine good question...I often wonder the same. I can only imagine maybe t is because more time is being spent on AngularConnect

**Comment by dweitz43** [comment]
i assume this may not be merged due to the breaking changes that are going to occur in alpha.9 of material listed here https://github.com/angular/material2/blob/master/CHANGELOG.md

**Comment by MateuszG** [comment]
Information: alpha.9 is realased @kodeine could you update PR to newest version?

**Comment by dweitz43** [comment]
@MateuszG i can look at this

**Pull request closed without merging**
