### PR TITLE
move configuration of HashLocationStrategy to environment.ts

### PR DESCRIPTION
**Pull request by ktong**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

It keeps default setting for LocationStrategy and it's easier to customize for different env.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by mastertinner** [comment]
Thanks for the PR @ktong! Can you please fix it so the tests are green?

**Comment by ktong** [comment]
fixed the lint error. However, still cannot pass the unit tests because test on HEAD is failed too.

**Comment by ktong** [comment]
redo it base on angular beta16

**Comment by ktong** [comment]
the test will pass after apply https://github.com/AngularClass/angular2-webpack-starter/pull/551

**Pull request closed without merging**
