### PR TITLE
docs: add angular2-seed (ghpabs) to list of seeds

### PR DESCRIPTION
**Pull request by ghpabs**

### CODE REVIEW

**Comment by gdi2290** [comment]
the name `angular2-seed` is already taken by @mgechev

**Comment by ghpabs** [comment]
To be fair I've got the `.io` domain so it pretty much makes my project the official one. (please don't take it seriously!)

Thanks for your help anyway.

**Comment by gdi2290** [comment]
if you name it `angular2-seed.io` then I can add it

**Comment by ghpabs** [comment]
Cool thanks.

**Pull request closed without merging**
