### PR TITLE
feature: use loader chain for resources when compiling AOT

### PR DESCRIPTION
**Pull request by shlomiassaf**
Enhancing AOT support from #885 #1298  ...

@d3viant0ne @colinskow @qdouble 

**What is the current behavior?** (You can also link to an open issue here)
When using AOT compilation, `@Component` templates (HTML, CSS, SCSS, etc...) are not running through the webpack loader chain.

Development output might not be the same as AOT output.

For example, CSS that goes through `postCSS` processing (autoprefixing, etc..) will not work when AOT compiling.  

If we want to use SCSS, html transformation or any other webpack goodie we can't.

* **What is the new behavior (if this is a feature change)?**
Use  [ngc wrapper](https://github.com/shlomiassaf/ngc-webpack) to provide resourced after they have passed the webpack loader chain, based on the webpack configuration provided.

The type of resource is irrelevant, if there's a loader configuration for it it will go through it.

### CODE REVIEW

**Comment by gdi2290** [comment]
lol amazing

**Comment by shlomiassaf** [comment]
@gdi2290 You fault.

 got me excited about AOT then my SCSS -> postCSS chain wouldn't work...

**Comment by gdi2290** [comment]
@shlomiassaf any idea why there is a ci error?

**Comment by shlomiassaf** [comment]
@gdi2290 Something in node 5...

```
> angular2-webpack-starter@5.1.1 ngc /home/travis/build/AngularClass/angular2-webpack-starter
> ngc-w -p tsconfig.webpack.json "--webpack" "config/webpack.prod.js"
keywords if/then/else require v5 option
Error: undefined, resolving symbol OpaqueToken in /home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/core/src/di/opaque_token.d.ts
    at simplifyInContext (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:25713:25)
    at StaticReflector.simplify (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:25725:15)
    at StaticReflector.annotations (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:25223:62)
    at NgModuleResolver.resolve (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:17583:84)
    at CompileMetadataResolver.getNgModuleMetadata (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:18091:62)
    at addNgModule (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:24985:60)
    at /home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:24996:16
    at Array.forEach (native)
    at _createNgModules (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:24995:28)
    at analyzeNgModules (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:24870:16)
    at analyzeAndValidateNgModules (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:24880:37)
    at AotCompiler.compileAll (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/@angular/compiler/bundles/compiler.umd.js:24604:20)
    at CodeGenerator.codegen (/home/travis/build/AngularClass/angular2-webpack-starter/modules/@angular/compiler-cli/src/codegen.ts:66:10)
    at /home/travis/build/AngularClass/angular2-webpack-starter/node_modules/src/main.ts:22:84
    at Object.main (/home/travis/build/AngularClass/tools/@angular/tsc-wrapped/src/main.ts:60:12)
    at main (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/src/main.ts:30:10)
    at Object.<anonymous> (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/src/main.ts:47:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
Compilation failed
```

i'll check in my local setup, I have v5

**Comment by shlomiassaf** [comment]
@gdi2290 ok, my bad...

I forgot to `require('reflect-metadata');`, it's in 6 not in 5
Will fix and post.

**Comment by DBosley** [comment]
@shlomiassaf Sorry to comment on an old post like this, but what did you do to resolve that error you posted above? I'm getting it in my own project when trying to compile with AOT

**Comment by tsm91** [comment]
@shlomiassaf this is awesome, thx a lot

**Pull request merged**
