### PR TITLE
feat: Add HardSourceWebpackPlugin

### PR DESCRIPTION
**Pull request by zigzag95**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add HardSourceWebpackPlugin in dev webpack config

* **What is the new behavior (if this is a feature change)?**
Reduce build time on src files change. Only impacted modules are rebuilt.

* **Other information**:
cf https://github.com/mzgoddard/hard-source-webpack-plugin

### CODE REVIEW

**Comment by zigzag95** [comment]
@gdi2290 need comments

**Comment by katallaxie** [comment]
@zigzag95 seems to be a case for the docs

**Comment by d3viant0ne** [comment]
I agree with @katallaxie, this is something that should be documented and not added.

**Comment by MarkPieszak** [comment]
@d3viant0ne Pat actually wanted this one in the Starter, see here: https://github.com/AngularClass/angular2-webpack-starter/issues/975

**Comment by gdi2290** [comment]
I see no downside to this unless someone can think of one. If this introduces gotchas for beginners then I would vote for moving it to docs

**Pull request closed without merging**
