### PR TITLE
Use local dependencies instead of global

### PR DESCRIPTION
**Pull request by xavifuefer**
removes potential conflicts with different versions

### CODE REVIEW

**Comment by gdi2290** [comment]
by default it does check local first or at least it's suppose to

**Comment by xavifuefer** [comment]
It wasn’t in my case and `npm install` threw an error when had to install the type files, because I didn’t have typings installed.

// Xavier Fuentes
LinkedIn <https://www.linkedin.com/in/xavifuentes> GitHub <https://github.com/xavifuefer> Twitter <https://twitter.com/xavifuefer>

**Comment by gdi2290** [comment]
alright then I'll merge it for sure

**Comment by gdi2290** [comment]
thanks! if you run into any more issues you can open an issue or make another pr :+1:

**Comment by xavifuefer** [comment]
will do! thanks for the awesome repo!

actually, this way you save 1 step on the “ÎQuick start", because you don’t need to do `typings install` manually, it’s in the `postinstall` script. :)

// Xavier Fuentes
LinkedIn <https://www.linkedin.com/in/xavifuentes> GitHub <https://github.com/xavifuefer> Twitter <https://twitter.com/xavifuefer>

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this email. Please notify the sender immediately by email and delete this email from your system.

♻️ Please consider the environment before printing this email

**Comment by gdi2290** [comment]
yeah I added it to the quick start but also in the postinstall in case they didn't read it. The idea is to ensure that the install works so if there is an error later on it's better later to learn about typings than in the start where the developer might assume it just doesn't work

**Comment by xavifuefer** [comment]
cool!

// Xavier Fuentes
LinkedIn <https://www.linkedin.com/in/xavifuentes> GitHub <https://github.com/xavifuefer> Twitter <https://twitter.com/xavifuefer>

**Pull request merged**
