### PR TITLE
Update Material2 Project URL

### PR DESCRIPTION
**Pull request by ysqi**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

docs update.

* **What is the current behavior?** (You can also link to an open issue here)

 material2 link error. page not found.

* **What is the new behavior (if this is a feature change)?**

change link with https://github.com/angular/material2

* **Other information**:

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@ysqi - change `branch` to `library`

**Comment by ysqi** [comment]
library branch?

**Comment by d3viant0ne** [comment]
No, there is no `material2` branch in this repo anymore which is what that documentation was originally referencing.

```
   <div>
     For material design components use the <a href="https://github.com/angular/material2"><b>material2</b></a> branch // <--- Library
    </div>	
```

**Comment by katallaxie** [comment]
🎱

**Pull request closed without merging**
